# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0cd83362792b4a192e57f12bcb5d7fad991a3acbd3d1fd8d73ab14e005b59aac6ff0a69d866996ae6f800d382e3726e941e7fa331ef2e9ab8d0a8eac9d8d37

test:
  secret_key_base: 029b64115a18ea4cfe671a0d265bec214f0b0e348b6d71a162b41a1a818dfc71b43759ea7872daf0b5ad40a1d3cc6ebe2deb4b98b15110a6a553356298c7ed28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
